Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -32,4 +32,4 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: pull
-        run: docker pull ${{ matrix.mirror }}/library/nginx |  echo "::error title=aaa::bbb"
+        run: docker pull ${{ matrix.mirror }}/library/nginx ||  echo "::error title=aaa::bbb"
